### ISSUE TITLE
Wrong results with gcc 8 + AVX

### ISSUE THREAD

**Issue by Sedeniono** [FFTW/fftw3#144] opened 2018-05-24 08:18 UTC
Hi,
I am currently trying to compile fftw 3.3.7 with the latest gcc 8.1.0 with AVX is enabled. Compilation works, but the results are completely wrong. I tried it on several Linux machines with Intel CPUs. The CPUs support AVX (e.g. one was a Intel Core i7-4770K).

Steps to reproduce:
- Download fftw 3.3.7 and extract
- From within the fftw directory: `./configure CC=gcc-8 --enable-avx` (or whatever for the `CC` part to force it to use the gcc 8 compiler).
- `make -j 8`
- `make check`. This fails early on. The start of the output is:
> Executing "...../fftw-3.3.7/tests/bench --verbose=1   --verify 'ok390o00' --verify 'ik390o00' --verify '//obr55x54' --verify '//ofr55x54' --verify 'obr55x54' --verify 'ibr55x54' --verify 'ofr55x54' --verify 'ifr55x54' --verify '//obc55x54' --verify '//ibc55x54' --verify '//ofc55x54' --verify '//ifc55x54' --verify 'obc55x54' --verify 'ibc55x54' --verify 'ofc55x54' --verify 'ifc55x54' --verify 'ok84bv16' --verify 'ik84bv16' --verify 'obrd5x4x12v10' --verify 'ibrd5x4x12v10' --verify 'ofrd5x4x12v10' --verify 'ifrd5x4x12v10' --verify '//obcd5x4x12v10' --verify '//ibcd5x4x12v10' --verify '//ofcd5x4x12v10' --verify '//ifcd5x4x12v10' --verify 'obcd5x4x12v10' --verify 'ibcd5x4x12v10' --verify 'ofcd5x4x12v10' --verify 'ifcd5x4x12v10' --verify 'ok10hx6o00x5e10v8' --verify 'ik10hx6o00x5e10v8' --verify 'obrd8x6x5*9' --verify 'ibrd8x6x5*9' --verify 'ofrd8x6x5*9' --verify 'ifrd8x6x5*9' --verify '//obcd8x6x5*9' --verify '//ibcd8x6x5*9' --verify '//ofcd8x6x5*9' --verify '//ifcd8x6x5*9' --verify 'obcd8x6x5*9' --verify 'ibcd8x6x5*9' --verify 'ofcd8x6x5*9' --verify 'ifcd8x6x5*9'"
ok390o00 3.71622e-16 6.66139e-15 3.20456e-16
ik390o00 3.6054e-16 5.66218e-15 3.67428e-16
//obr55x54 4.37728e-16 2.60761e-15 6.58113e-16
//ofr55x54 4.2855e-16 2.08608e-15 9.4669e-16
Found relative error 1.617482e+00 (freq shift)

No problems occur with gcc 7.3.0 and earlier versions.
Moreover, replacing `--enable-avx` with `--enable-avx2` also leads to the wrong results. Just using `--enable-sse2` works, however.

According to https://gcc.gnu.org/gcc-8/changes.html several optimizations were improved. Maybe one of these is the issue?

**Comment by matteo-frigo** [comment] 2018-05-24 10:53
Thanks for the bug report.  I can reproduce the problem.  It looks like the smallest reproducer
is a 1D transform of length 3 (see below).   I'll dig deeper later today.

FFTW has a long history of finding compiler bugs, unfortunately.

athena@amd-sid:fftw-3.3.7$ ./tests/bench -o paranoid -v8 3
Planning 3...
using plan_dft_1d
estimate-planner time: 0.000317 s
using plan_dft_1d
(dft 0 0 0 1 1 ((3 2 2)) ()):
  (dft-direct-3 "n1fv_3_avx")
cost 93.6562  

Found relative error 1.031403e+00 (linear)
       0   0.010946940203  -0.011095186178     0.010946940203  -0.011095186178
       1   0.165480290483  -0.069830420451     0.040435802279  -0.072154527248
       2  -0.003807183450  -0.123174157583     0.121237304754  -0.120850050786

**Comment by matteo-frigo** [comment] 2018-05-24 11:45
Should be fixed now.  As a workaround, compile without '-ffast-math'.  The default configure script chooses -ffast-math in the CFLAGS, so you must remove it explicitly.

See 19eeeca5 and 41b0d9ef for the full story.

I'll keep testing myself, but please report any further problems.

**Closed by matteo-frigo** 2018-05-24 11:45 UTC
